### ISSUE TITLE
NFE fission reactors patch isn't adding SystemHeat to 2.5 m and larger reactors

### ISSUE THREAD

**Issue by danfarnsy** [ChrisAdderley/SystemHeat#13]
For reactor-25 and larger fission reactors, SystemHeat doesn't appear to be adding any modules to the parts. I can't tell immediately from looking at NearFutureElectricalReactors.cfg why this should be. This is occurring in both the 1.9.1 and 1.10.1 test installs I used.

![screenshot3](https://user-images.githubusercontent.com/13547273/91678607-3849a080-eb03-11ea-8266-678ac4790c0c.png)

**Comment by Gordon-Dry** [comment]
I was testing SystemHeat for a short period, but as it's not compatible to Kerbalism at all I wikll remove it now.
But I stumbled upon this:
https://github.com/ChrisAdderley/SystemHeat/blob/2484ee801fc6e964ac5b9f1d1348294284f582c5/Extras/SystemHeatFissionReactors/NearFutureElectrical/NearFutureElectricalReactors.cfg#L355
It should be reactor-375-2

**Comment by ChrisAdderley** [comment]
All fixed
